cozy/create-cozy-app

packages/cozy-scripts/template/app/src/targets/browser/index.jsx
Use simple hot reloading. Internal component state will not be preserved. Redux state will be preserved though.
=> Simple hot reloading

packages/cozy-scripts/template/app/src/targets/browser/index.ejs
Only for `__TARGET__ !== mobile`
=> fix: add font stack from stack

packages/cozy-scripts/template-vue/package.json, packages/cozy-scripts/template-vue/yarn.lock
Since it will be installed by the CLI
=> Remove cozy-scripts from template-vue dependencies

README.md
=> fix: english mistakes

README.md
=> Update illustration in README

packages/cozy-scripts/config/webpack.config.eslint.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
=> Eslint improvements

packages/cozy-scripts-vanilla/scripts/init.js, packages/cozy-scripts-vanilla/template/manifest.webapp, packages/cozy-scripts-vanilla/test/scripts.spec.js, packages/cozy-scripts/scripts/init.js, packages/cozy-scripts/template-vue/manifest.webapp, packages/cozy-scripts/template/manifest.webapp, packages/cozy-scripts/test/scripts-vue.spec.js, packages/cozy-scripts/test/scripts.spec.js
`category` manifest field has been replaced by `categories` array to handle many categories
=> Remove category question and use `categories` array

packages/cozy-scripts/README.md, packages/cozy-scripts/bin/cozy-scripts.js, packages/cozy-scripts/scripts/build.js, packages/cozy-scripts/scripts/config.js, packages/cozy-scripts/scripts/standalone.js, packages/cozy-scripts/scripts/watch.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap, packages/cozy-scripts/test/scripts-vue.spec.js, packages/cozy-scripts/test/scripts.spec.js
`browser:production` for build script and `browser:development` for the others
=> Better handling NODE_ENV and build options with scripts/CLI

packages/cozy-scripts/scripts/watch.js
=> Display stats in watch script only if defined

packages/cozy-scripts/template-vue/package.json, packages/cozy-scripts/template/package.json
Can be useful to get rid of some weird missing modules issues.
=> Add app script to reset yarn lockfile

packages/cozy-scripts/config/webpack.config.vue.js, packages/cozy-scripts/template-vue/package.json, packages/cozy-scripts/template-vue/yarn.lock, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
The breaking will be handled correctly with new version of eslint-config and babel-preset to come.
=> Temporary downgrade breaking vue-loader from v15 to v14

packages/cozy-scripts/config/webpack.config.pictures.js, packages/cozy-scripts/config/webpack.config.preact.js, packages/cozy-scripts/config/webpack.environment.dev.js, packages/cozy-scripts/config/webpack.vars.js, packages/cozy-scripts/package.json, packages/cozy-scripts/scripts/standalone.js, packages/cozy-scripts/template-vue/package.json, packages/cozy-scripts/template/app/src/targets/browser/index.jsx, packages/cozy-scripts/template/package.json, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap, packages/cozy-scripts/test/scripts-vue.spec.js, packages/cozy-scripts/test/scripts.spec.js, packages/cozy-scripts/yarn.lock
This PR adds the Hot Module Reload (without persisting state) for the React and Vue applications.
=> Add hot-module-reload feature for React/Vue

packages/cozy-scripts-vanilla/template/index.html, packages/cozy-scripts-vanilla/template/view2.html, packages/cozy-scripts/template-vue/app/src/targets/browser/index.ejs, packages/cozy-scripts/template/app/src/targets/browser/index.ejs
=> feat: support iphonex meta

packages/cozy-scripts/template-vue/app/src/components/App.vue, packages/cozy-scripts/template-vue/app/test/__snapshots__/app.spec.js.snap, packages/cozy-scripts/template/app/src/components/App.jsx, packages/cozy-scripts/template/app/test/__snapshots__/app.spec.js.snap
Use the new Layout react component from cozy-ui and fix the class name in the Vue template
=> Fix app layout issue using new Cozy-UI

packages/cozy-scripts/config/webpack.config.base.js, packages/cozy-scripts/config/webpack.config.cozy-ui.js, packages/cozy-scripts/config/webpack.config.cozy-ui.react.js, packages/cozy-scripts/config/webpack.config.css-modules.js, packages/cozy-scripts/config/webpack.config.eslint.js, packages/cozy-scripts/config/webpack.config.manifest.js, packages/cozy-scripts/config/webpack.config.pictures.js, packages/cozy-scripts/config/webpack.config.preact.js, packages/cozy-scripts/config/webpack.config.services.js, packages/cozy-scripts/config/webpack.config.vue.js, packages/cozy-scripts/config/webpack.environment.dev.js
Will fix some loaders not found issues.
=> Add `require.resolve` to all loaders

packages/cozy-scripts/config/webpack.config.pictures.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Images were not loaded correctly due to this wrong publicPath
=> Fix wrong images webpack publicPath

packages/babel-preset-cozy-app/yarn.lock, packages/cozy-scripts/template-vue/yarn.lock, packages/cozy-scripts/template/yarn.lock, packages/cozy-scripts/yarn.lock, renovate.json
The lockfile maintenance was causing a lot of conflicts in PRs with lockfiles.
=> Disable renovate lockfile maintenance feature + reset some lockfiles

packages/cozy-scripts/template-vue/app/jest.config.js, packages/cozy-scripts/template/app/jest.config.js
JSDOM issue : https://github.com/facebook/jest/issues/6766
=> Fix jest URL issue with jsdom

packages/cozy-scripts/package.json, packages/cozy-scripts/yarn.lock
Unused since the introduction of Prettier.
=> Remove unused standardjs dependencies

packages/cozy-scripts/bin/cozy-scripts.js
=> Add better command description for cozy-scripts

packages/cozy-scripts/README.md, packages/cozy-scripts/bin/cozy-scripts.js, packages/cozy-scripts/scripts/release.js, packages/cozy-scripts/test/scripts-vue.spec.js, packages/cozy-scripts/test/scripts.spec.js
* ~~Import the shell script from [@gregorylegarec repository](https://github.com/gregorylegarec/cozy-release)~~ Done in cozy-libs
* ~~Add a `--help` command to the cozy-release script~~ Done in cozy-libs
* Add it as `cozy-scripts release` CLI + add tests
* Add documentation
@gregorylegarec Feel free to complete this PR if you see some changes to do :)
=> Add new cozy-scripts `release` CLI

packages/cozy-scripts/config/webpack.config.eslint.js, packages/cozy-scripts/config/webpack.environment.dev.js, packages/cozy-scripts/docs/webpack-configs.md, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
* Fix cozy-bar css include path
* Avoid emitting eslint errors on production or if hot reload enabled (ping @ptbrowne)
=> Development config improvements

packages/cozy-scripts/config/webpack.bundle.preact.js, packages/cozy-scripts/config/webpack.config.react.js, packages/cozy-scripts/docs/webpack-configs.md, packages/cozy-scripts/template/package.json, packages/cozy-scripts/template/yarn.lock, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
This PR also adds a specific bundle with preact usage (same than the previous default bundle)
=> Use now react by default instead of preact

README.md, packages/cozy-scripts/README.md, packages/cozy-scripts/bin/cozy-scripts.js, packages/cozy-scripts/config/webpack.config.eslint.js, packages/cozy-scripts/config/webpack.config.services.js, packages/cozy-scripts/config/webpack.vars.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
format automatically the code with eslint when I watch code, examples:
```
yarn watch --fix
yarn standalone --fix
```
=> Add --fix on cozy-scripts

packages/cozy-scripts-vanilla/template/index.html, packages/cozy-scripts-vanilla/template/view2.html, packages/cozy-scripts/template-vue/app/src/targets/browser/index.ejs, packages/cozy-scripts/template/app/src/targets/browser/index.ejs
Add `{{.AppNamePrefix}}` and `{{.AppSlug}}`
=> Update html files for new stack variables

packages/cozy-scripts/config/webpack.config.react.js, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Necessary for cozy-ui usage with React since it will be added a Preact retrocompatibility
Related to https://github.com/cozy/cozy-ui/pull/629/files
=> Add `USE_REACT` env variable for cozy-ui

packages/cozy-scripts/config/webpack.environment.dev.js, packages/cozy-scripts/package.json, packages/cozy-scripts/scripts/start.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap, packages/cozy-scripts/yarn.lock
`writeToDisk` is a recent configuration added to webpack, it allows to do the same thing than `write-file-webpack-plugin`
=> Use writeToDisk intead of webpack plugin

packages/cozy-scripts/template-vue/app/renovate.json, packages/cozy-scripts/template/app/renovate.json
Use cozy config from https://github.com/cozy/cozy-libs/tree/master/packages/renovate-config-cozy
=> chore: Use renovate cozy config

packages/cozy-scripts/template-vue/.travis.yml, packages/cozy-scripts/template-vue/package.json, packages/cozy-scripts/template/.travis.yml, packages/cozy-scripts/template/package.json
I don't understand why we launch lint when I launch my test?
=> feat: Remove lint command on test

packages/cozy-scripts/config/webpack.environment.dev.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap, packages/cozy-scripts/utils/paths.js
Avoid false positive for specific environment needs (Preact/React compat)
=> Better assets include for dev (bar,client-js)

packages/cozy-scripts/config/webpack.config.base.js, packages/cozy-scripts/config/webpack.config.services.js, packages/cozy-scripts/config/webpack.target.browser.js, packages/cozy-scripts/config/webpack.vars.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Will be better to recognise code source while debugging interapps.
=> Use app slug int output filename

packages/cozy-scripts/template-vue/app/src/targets/browser/index.ejs, packages/cozy-scripts/template/app/src/targets/browser/index.ejs
See https://www.w3.org/TR/appmanifest/#obtaining
Thanks @nono for this fix.
=> Send cookies when fetching manifest.json

packages/cozy-scripts/scripts/test.js, packages/cozy-scripts/utils/paths.js
It was breaking passing custom config file through `--config`
=> Don't automatically pass config to jest

packages/cozy-scripts/config/webpack.config.chunks.js, packages/cozy-scripts/config/webpack.config.intents.js, packages/cozy-scripts/config/webpack.target.browser.js, packages/cozy-scripts/config/webpack.target.mobile.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Avoid having multiple unnecessary multiple split chunks
=> Use only one vendors chunk

packages/cozy-scripts/config/webpack.target.mobile.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
This is needed for the cozy-bar to work on mobile.
=> fix: Expose react/preact on mobile

packages/cozy-scripts/package.json, packages/cozy-scripts/yarn.lock
See https://github.com/webpack/webpack-dev-server/issues/851#issuecomment-449518624
=> Downgrade to DevServer 3.1.10 to avoid host checking bug

packages/cozy-scripts/config/webpack.config.public.js, packages/cozy-scripts/config/webpack.environment.dev.js, packages/cozy-scripts/config/webpack.vars.js, packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Fix public assets in development mode
Fix #1041
=> Handling public assets

packages/cozy-scripts/package.json, packages/cozy-scripts/yarn.lock
See https://github.com/CPatchane/create-cozy-app/pull/1014
=> fix: Downgrade webpack-dev-server to avoid host checking bug

packages/cozy-scripts/scripts/lint.js, packages/cozy-scripts/template-vue/app/src/components/App.vue, packages/cozy-scripts/template-vue/app/src/components/Icon.vue, packages/cozy-scripts/test/scripts-vue.spec.js, packages/cozy-scripts/test/scripts.spec.js
* Throw error if linting failed
* Fix vue app linting issues
=> Make lint script failed correctly + fix vue app linting issues

packages/cozy-scripts/template-vue/.travis.yml, packages/cozy-scripts/template/.travis.yml
Some config cleaning + use stages for better Travis CI build
=> Improve app travis config

packages/cozy-scripts/template/app/test/components/Todos/__snapshots__/todoAdd.spec.js.snap, packages/cozy-scripts/template/app/test/components/Todos/__snapshots__/todoRemoveButton.spec.js.snap, packages/cozy-scripts/template/app/test/components/Todos/todoAdd.spec.js, packages/cozy-scripts/template/app/test/components/Todos/todoRemoveButton.spec.js
Was using also wrong snapshots
=> Wrong test for some React components

.travis.yml, package.json, scripts/integration-test.sh
- Clone banks
- yarn install
- yarn add cozy-scripts@local-copy
- yarn build
=> feat: Add integration test

packages/cozy-scripts/package.json, packages/cozy-scripts/scripts/build.js, packages/cozy-scripts/scripts/deploy.js, packages/cozy-scripts/yarn.lock
- Logging of build errors
- Add git-directory-deploy as dependency
=> Improvements

packages/cozy-scripts/package.json, packages/cozy-scripts/yarn.lock
=> fix: ReactHotLoader is used in webpack config react

packages/cozy-scripts/template/app/src/targets/browser/index.jsx
Otherwise the theme cannot correctly initialize, see
https://github.com/cozy/cozy-ui/issues/1774#issuecomment-803967934
=> fix: Import cozy-ui CSS as early as possible

packages/cozy-scripts/template/.travis.yml, packages/cozy-scripts/template/app/.tx/config, packages/cozy-scripts/template/package.json, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
We do not use transifex this way. We now store the tranlasted files
in the repository and plug transifex to create Pull Request on it
when change are done there.
=> feat: Remove tx installation

packages/cozy-scripts/scripts/init.js, packages/cozy-scripts/template/app/src/targets/browser/index.ejs, packages/cozy-scripts/template/manifest.json, packages/cozy-scripts/template/package.json, packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap, packages/create-cozy-app/create-cozy-app.js
- Ajout du fichier `manifest.json` au template (voir https://github.com/cozy/create-cozy-app/issues/1413)
=> feat: Add manifest.json to template

packages/cozy-scripts/docs/webpack-configs.md
=> docs: Fix broken link

packages/cozy-scripts/config/webpack.config.manifest.js
Today, in the Store, in the details of an application,
we cannot add screenshots keeping the translations
in the `locales` folder
It is now possible to keep the translations in the `locales`
folder and simply add the path of the screenshots
in the `manifest.webapp` file:
Ex:
```
"locales": {
"en": {
"screenshots": [
"screenshots/en/screenshot01.png",
"screenshots/en/screenshot02.png",
]
},
"fr": {
"screenshots": [
"screenshots/fr/screenshot01.png",
"screenshots/fr/screenshot02.png",
]
}
}
```
=> fix: Merge locales and langs entry in manifest

packages/cozy-scripts/config/webpack.config.manifest.js
The translations of the manifest were generated from the files present in the locales folder of the application. However, some files are only useful for the application. Now, when you define languages ​​in the manifest only the locals of it are integrated.
This PR aims to fix an issue on `cozy-store` where for the languages of `cozy-notes` there is an language call `app_langs.atlassian_missing_french`. This language is an locale file use internally by cozy-notes.
=> fix: Filter manifest locales by correlating manifest langs

packages/cozy-scripts/config/webpack.config.pictures.js, packages/cozy-scripts/package.json, packages/cozy-scripts/test/scripts.spec.js, packages/cozy-scripts/yarn.lock
We want to keep static images used by cozy-ui inside components
=> feat: Copy static images from transpiled/react
