- packages/cozy-scripts/template/app/src/targets/browser/index.jsx
If you want to use pouch, you need to specify a protocol for the URL.
> chore: add protocol to cozy client js init

- packages/cozy-scripts/config/webpack.target.mobile.js
Sinon pour un build de prod sur mobile on a le build de la cozy-bar en mode non production et du coup on a un warning comme ceci :
> chore: Use the production build of cozy libs

- packages/cozy-scripts/config/webpack.config.progress.js
- packages/cozy-scripts/package.json
- packages/cozy-scripts/scripts/watch.js
- packages/cozy-scripts/yarn.lock
Issue:
```
myapptest/node_modules/cozy-scripts/node_modules/chalk/index.js:82
const open = ansiStyles.color[levelMapping[level]][model].apply(null, arguments);
^
TypeError: Cannot read property 'hex' of undefined
at Function.<anonymous> (myapptest/node_modules/cozy-scripts/node_modules/chalk/index.js:82:55)
at Object.<anonymous> (myapptest/node_modules/cozy-scripts/utils/_colorize.js:7:15)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
```
See https://github.com/chalk/chalk/issues/248
> Downgrade chalk to v2.2.2 due to undefined issue

- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
By default it's enabled by webpack and symlinked resources are resolved to their real path, not their symlinked location.
> Disable webpack symlinks resolving

- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/cozy-scripts/utils/paths.js
Was previously built directly in `build/` folder.
> Build services in `build/services/` folder instead of `build/`

- packages/cozy-scripts/config/webpack.config.pictures.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
The goal of this PR is to made images work when we are not at website root.
For example in `http://collect-greg.mycozy.cloud/intents/`.
> feat: add root in image path in webpack config ✨

- packages/eslint-config-cozy-app/index.js
- packages/eslint-config-cozy-app/package.json
- packages/eslint-config-cozy-app/yarn.lock
This way we can run prettier then eslint.
https://stackoverflow.com/questions/44690308/whats-the-difference-between-prettier-eslint-eslint-plugin-prettier-and-eslint
> feat: turn off rules that are not compatible with prettier.

- packages/cozy-scripts/scripts/init.js
- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/test/scripts-vue.spec.js
- packages/cozy-scripts/test/scripts.spec.js
We used to ask for the user email for the Travis deployment script.
Now we use deploy@travis-ci.org by default for this script.
So we can remove this email CLI question.
> Remove email CLI question + use default travis email to deploy

- packages/cozy-scripts/template-vue/app/.prettierrc
- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template/app/.prettierrc
- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/eslint-config-cozy-app/index.js
- packages/eslint-config-cozy-app/package.json
- packages/eslint-config-cozy-app/yarn.lock
Drop Standard configuration and use `eslint:recommended` and prettier. I also kept `eslint-plugin-react`.
There is a question and a potential problem : 
Do we need to keep other plugins (`eslint-plugin-promise`, `eslint-plugin-import`, `eslint-plugin-node`) ?
And the [eslint-plugin-prettier documentation](https://github.com/prettier/eslint-plugin-prettier#options) says that : 
> While it is possible to pass options to Prettier via your ESLint configuration file, it is not recommended because editor extensions such as prettier-atom and prettier-vscode will read .prettierrc, but won't read settings from ESLint, which can lead to an inconsistent experience.
This can be annoying for some people, what do you think about it ?
I tested this configuration on Banks with `--fix` flag, it worked …
> feat: drop standardjs in favor of prettier in eslint config

- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template/package.json
The goal of this PR is to avoid having the error message `sh: /bin/rm: Argument list too long` when running `rm *` on a huge `build` directory.
The main idea is to use a find command, [as shown here](https://wiki.debian.org/CommonErrorMessages/ArgumentListTooLo).
Also, we can filter on root folder by using `! -name 'build'`, [like explained here](https://superuser.com/questions/397307/how-to-ignore-certain-filenames-using-find/397325#397325)
> chore: better clean tasks 📝

- packages/cozy-scripts/template-vue/app/renovate.json
- packages/cozy-scripts/template/app/renovate.json
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
We recommend this configuration of the [renovate app](https://renovateapp.com) to maintain all the application dependencies up to date by opening pull requests automatically (`yarn` and lockfile handled).
> Add renovate.json config files to templates

- .travis.yml
- README.md
- packages/create-cozy-app/README.md
- packages/create-cozy-app/index.js
The new `fs-extra` (v6) now supports only node 8+
> Use now node 8+ (drop v6 and v7 support)

- packages/babel-preset-cozy-app/README.md
- packages/babel-preset-cozy-app/index.js
- packages/babel-preset-cozy-app/package.json
- packages/babel-preset-cozy-app/yarn.lock
Now you can pass an option to target Node instead of browsers for transpiling: 
```json
{
"presets": [
["cozy-app", {
"node": true
}]
]
}
```
Preset options documentation: https://babeljs.io/docs/plugins/#pluginpreset-options and https://github.com/babel/babel/tree/master/packages/babel-helper-plugin-utils/src#babelhelper-plugin-utils
> Split presets in babel-preset-cozy-app

- packages/eslint-config-cozy-app/README.md
- packages/eslint-config-cozy-app/basics.js
- packages/eslint-config-cozy-app/index.js
- packages/eslint-config-cozy-app/package.json
- packages/eslint-config-cozy-app/react.js
Two shareable configurations now available:
```javascript
// for main JS code
extends: [ 'cozy-app']
// for react app
extends: ['cozy-app/react']
```
Documentation about multiple configs from a shareable config: https://eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs
> Split configurations in eslint-config-cozy-app

- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Fix #372 
Use the `node` option with `babel-preset-cozy-app` and the "js only" config from `eslint-config-cozy-app` for services.
> Use simpler babel config for services

- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/template-vue/app/.babelrc
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Disable `react` needs for these files.
> Better usage of babel-preset cozy-app for `.js` files

- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template/package.json
For some weird reasons, `eslint-plugin-prettier` is missing in the application modules. Let's add it to the package while figuring out this issue.
> Add buggy asked eslint-plugin-prettier

- packages/cozy-scripts/scripts/standalone.js
Change environment variables HOST/PORT for webpack server to add `DEV_` prefix, better to avoid conflicts
> Change PORT/HOST variables to DEV_PORT/DEV_HOST

- packages/cozy-scripts/config/webpack.target.browser.js
`name` in `package.json` is often in slug form like "cozy-contacts"
`name` in `manifest.webapp` is the one used in the store so it has a more humane form.
> feat: HTML title from manifest

- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template-vue/yarn.lock
- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/template/yarn.lock
This commit adds eslint plugins used by the apps (vue and react).
For some weird reasons, the build is often broken due to these missing
dependencies (maybe a yarn issue). So we add them until the issue is fixed.
> Add often missing eslint plugins into apps

- packages/cozy-scripts/config/webpack.config.intents.js
- packages/cozy-scripts/config/webpack.target.browser.js
- packages/cozy-scripts/config/webpack.target.mobile.js
Use the app name with the prefix (if exists) for all HTML titles.
> Use the correct app name for html titles

- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template/package.json
Add the prebuild script to lint before the build in templates (also useful to enable transifex pulling before the build).
> Add pretest script in templates

- packages/cozy-scripts/utils/cleanBuild.js
Unnecessary to test if folder exist because fs-extra is [extra](https://github.com/jprichardson/node-fs-extra/blob/master/docs/emptyDir.md).
fix #644
> fix: Docker unlink folder 🐛

- packages/babel-preset-cozy-app/README.md
- packages/babel-preset-cozy-app/index.js
Sometimes it could break CSPs, so this adds a way to disable it.
> Add transformRegenerator option to babel-preset-coz-app

- packages/cozy-scripts/config/webpack.config.vendors.js
SVGO is removing viewBox attributes from SVG icon but if this attribute is missing, the icon may be rendered vertically stretched.
> Disable removeViewBox from SVGO

- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/template/yarn.lock
Reverts CPatchane/create-cozy-app#789
For some very weird reasons, it's breaking the build with this kind of erros related to some cozy-ui `.jsx` files:
```
Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got null
```
> Revert "chore(deps): update dependency cozy-client to v2.21.1"

- packages/cozy-scripts/package.json
- packages/cozy-scripts/stack/disableCSP.yaml
- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template/package.json
Since CSPs break hot reloading we have to disable them. 
This PR add a dedicated config file and an app script to launch the stack using Docker with CSPs disabled
> Add `stack:nocsp` app script for HMR

- packages/cozy-scripts/scripts/start.js
The quitStack script wasn't stoppig correctly, and eating CPU in the background
> Fix: Exiting the script stops docker correctly

- packages/cozy-scripts/package.json
The dependency was not in the `dependencies` field of the package.json but in `devDependencies`
> Add missing postcss-discard-empty dependency

- packages/cozy-scripts/config/webpack.environment.dev.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
We should always write files on disk when developing since we can run `start` without `--hot` and it will break the docker part (because assets not found).
The write plugin now only writes assets (no `.js` and `.css` files) to be able to run the docker stack correctly while keeping using build files (css,js) from the memory.
> Always write files on dev mode

- packages/cozy-scripts/bin/cozy-scripts.js
- packages/cozy-scripts/scripts/lint.js
- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template-vue/yarn.lock
- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/template/yarn.lock
- packages/cozy-scripts/utils/paths.js
This adds a `lint` script that uses `eslint`.
I find it useful to pass the `argv`, so the user can add custom attributes to the script, just as he would do with raw eslint. What do you think ?
The only thing that bothers me is that the output is not colored. If you know how we can fix this, tell me :)
I have another implementation that uses the [eslint's node API](https://eslint.org/docs/developer-guide/nodejs-api) but I felt it was more difficult to get the same level of flexibility without reimplementing some parts of the original eslint's CLI. So I think that even if using the node API seems more elegant, executing a child process is more efficient.
> feat: Add lint script

- packages/cozy-scripts/config/webpack.environment.prod.js
- packages/cozy-scripts/package.json
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/cozy-scripts/yarn.lock
This could fix an issue due to Uglify default with Webpack 4: `TypeError: Super expression must either be null or a function`. 
Terser is recommended and [will be used by default by Webpack 5](https://github.com/webpack-contrib/terser-webpack-plugin/issues/15#issuecomment-421388132)
Also more info there: https://twitter.com/dan_abramov/status/1060226280619163649
> Prefer Terser for optimization with Webpack

- packages/cozy-scripts/template/app/src/components/Todos/TodoRemoveButton.jsx
There was a message of React saying that we try to change the state of an unmounted component. Here the component is unmounted by update when the client has deleted the document.
> Don't change state of unmounted component in React template

- packages/cozy-scripts/config/webpack.target.browser.js
- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template-vue/yarn.lock
- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/template/yarn.lock
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/cozy-scripts/utils/exposer.js
- packages/cozy-scripts/utils/paths.js
- packages/cozy-scripts/utils/preactExposer.js
- packages/cozy-scripts/utils/reactExposer.js
~~This was breaking the application with the new CozyBar since we need these packages for the exposing React feature due to the requires [here](https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/utils/exposer.js#L4-L5) (even if we only use React)~~
Edit: Use two separated exposer files for React and Preact which avoid looking for Preact and React during parsing.
> Split React and Preact exposer into two exposers

- packages/cozy-scripts/scripts/init.js
Handle `.travis.yml`, `.gitignore`, `yarn-error.log` files in case or init error
> Add more expected filenames for init error handling

- packages/cozy-scripts/scripts/init.js
The slug can be different from the folder name
>  Use the correct folder name in finish logs

- packages/cozy-scripts/README.md
- packages/cozy-scripts/bin/cozy-scripts.js
- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/config/webpack.config.cozy-ui.js
- packages/cozy-scripts/config/webpack.config.cozy-ui.react.js
- packages/cozy-scripts/config/webpack.config.hash.js
- packages/cozy-scripts/config/webpack.config.intents.js
- packages/cozy-scripts/config/webpack.config.manifest.js
- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/config/webpack.config.vendors.js
- packages/cozy-scripts/config/webpack.environment.dev.js
- packages/cozy-scripts/config/webpack.target.browser.js
- packages/cozy-scripts/config/webpack.target.mobile.js
- packages/cozy-scripts/config/webpack.vars.js
- packages/cozy-scripts/scripts/lint.js
- packages/cozy-scripts/scripts/start.js
- packages/cozy-scripts/test/__snapshots__/cli.spec.js.snap
- packages/cozy-scripts/test/cli.spec.js
- packages/cozy-scripts/utils/cleanBuild.js
- packages/cozy-scripts/utils/paths.js
* More robust paths file usage by using as functions
* Add CLI more options to provide custom application paths: `--src-dir`, `--build-dir`, `--manifest`
> Use paths as functions + handle more CLI path options

- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
In mobile apps, we need to load the fonts along with the rest of the assets, but there's no loader configured for them at the moment.
> feat: Added loader for font files

- packages/cozy-scripts/config/webpack.target.mobile.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
This is more a suggestion, but every other `target` uses `inject: false` — so if you use the same template on mobile, things go very wrong. It's a breaking change but I think it makes things homogeneous and makes more sense.
> feat: BREAKING CHANGE don't auto-inject mobile chunks (mobile target only)

- packages/cozy-scripts/config/webpack.config.chunks.js
- packages/cozy-scripts/config/webpack.config.intents.js
- packages/cozy-scripts/config/webpack.config.public.js
- packages/cozy-scripts/config/webpack.vars.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
* Build all app files into `build/app`
* Build all vendors files into `build/vendors`
* Build all intents files into `build/intents`
* Build all public files into `build/public`
Since the `.html` files don't change place, this concerns only paths computed by Webpack so this is not a breaking change.
Need context: The cozy-stack need to have all files in the `public/` folder to server public (not authenticated) pages
> Build intents and public chunks in specific folders

- packages/cozy-scripts/config/webpack.config.pictures.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
All resources used by the public pages must be in a public folder or subfolder in order to be put correctly in `build/public` in order to be hanlde as public by the stack
> Better handling public assets

- packages/cozy-scripts/bin/cozy-scripts.js
- packages/cozy-scripts/utils/regexpReplacer.js
When using `--show-config`, `module.rules.test` were shown as empty object (`{}`). This is due to how `JSON.stringify` treats regexp objects. I added a replacer function that calls `toString` on regexp during stringify process. So now when we have `test: /\.css$/`, `--show-config` outputs `"test": "/\\.css$/"`.
> feat(cozy-scripts): Show regexp when using --show-config flag

- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/config/webpack.vars.js
Since we need to specify services files name into the manifest we can't have a dynamic hash into the name.
> Don't use hash for services files name

- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Externals was making webpack not including all dependencies into services builds.
> Remove externals property for services build

- packages/cozy-scripts/config/webpack.bundle.default.js
- packages/cozy-scripts/config/webpack.bundle.preact.js
- packages/cozy-scripts/config/webpack.bundle.vue.js
- packages/cozy-scripts/config/webpack.config.intents.js
- packages/cozy-scripts/config/webpack.config.public.js
- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
* Add services config by default to bundles (if services files detected, it will be handled)
* Build intents and public entries only if target `browser`
> Handle services by default + build public/intents only for browser target

- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/config/webpack.vars.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Following what we did in banks (see https://github.com/cozy/cozy-banks/pull/703).
This enables us to provide some flags that should be enabled when we build an app. For example: `COZY_FLAGS=balance-panels yarn build`.
This is useful when we want to make a build to validate a feature that is behind a flag, for example. It pairs nicely with `deploy2cozy`: `COZY_FLAGS=balance-panels deploy2cozy` will build the app with `balance-panels` flag turned on and deploy it to a temporary instance. The feature, even if behind a flag, can now be easily validated. Same goes for mobile apps.
> feat(cozy-scripts): Handle flags at build time

- packages/cozy-scripts/config/webpack.config.intents.js
- packages/cozy-scripts/config/webpack.config.public.js
- packages/cozy-scripts/config/webpack.target.browser.js
- packages/cozy-scripts/config/webpack.target.mobile.js
- packages/cozy-scripts/config/webpack.vars.js
We expose React or Preact on Public and Intent page. 
But if you can explain to me why we need to add that stuff here since it's already in browser.config.js and since we already defined : `process.env[CTS.USE_PREACT] = true` in the preact.conf.
> fix(public/intent): React / Preact config

- packages/cozy-scripts/config/webpack.config.progress.js
- packages/cozy-scripts/package.json
- packages/cozy-scripts/utils/progress.js
- packages/cozy-scripts/yarn.lock
* Copy/paste code form node-progress, since it seems to be unmaintained (from now, until doing a fork maybe)
* Add some fixes from unmerged node-progress PRs (thanks @ptbrowne and @jHoldroyd)
* Add an offset option to have right margin for longer webpack messages
> Fix progress bar width overflow

- packages/cozy-scripts/config/webpack.config.pictures.js
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
We should not use absolute path for outputPath since it will try to make directory in root.
Fix #1072
> Don't use absolute outputPath for file-loader

- packages/cozy-scripts/scripts/start.js
Avoid having different behaviour between a classic `watch` and a `start`
> Remove hash usage for dev-server + provide contentBase option

- packages/cozy-scripts/config/webpack.config.cozy-ui.react.js
- packages/cozy-scripts/template-vue/app/src/styles/index.css
- packages/cozy-scripts/template-vue/app/src/styles/index.styl
- packages/cozy-scripts/template-vue/package.json
- packages/cozy-scripts/template-vue/yarn.lock
- packages/cozy-scripts/template/app/src/styles/index.css
- packages/cozy-scripts/template/app/src/styles/index.styl
- packages/cozy-scripts/template/app/test/components/Todos/__snapshots__/todoAdd.spec.js.snap
- packages/cozy-scripts/template/package.json
- packages/cozy-scripts/template/yarn.lock
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Use transpiled cozy-ui components for react template.
Also use only `.css` files in templates
Upgrade cozy-ui to v19
Breaking change since cozy-scripts won't build untranspiled cozy-ui components styles anymore
> Use only transpiled UI React components + upgrade cozy-ui to v19

- packages/cozy-scripts-vanilla/template/index.html
- packages/cozy-scripts-vanilla/template/view2.html
- packages/cozy-scripts/template-vue/app/src/targets/browser/index.ejs
- packages/cozy-scripts/template/app/src/targets/browser/index.ejs
The users may have a flash of unstyled content without this fix: browsers don't wait that the CSSOM is ready to execute <script> with the defer attribute. It means that they can render before the CSS have been parser, and SVG icons are often rendered on the full screen in that case.
> fix: :fire: Avoid the glitch while loading the app

- packages/cozy-scripts/config/webpack.target.browser.js
- packages/cozy-scripts/config/webpack.target.mobile.js
- packages/cozy-scripts/docs/webpack-configs.md
- packages/cozy-scripts/package.json
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/cozy-scripts/yarn.lock
The defer attribute for the scripts is not a good idea in the cozy context. We have small HTMLs, so we don't really benefit from it, and it can make the browsers execute the scripts before the CSS has been
loaded (flash of unstyled content).
> fix: :wrench: Do not use defer for scripts

- packages/cozy-scripts/config/webpack.environment.prod.js
- packages/cozy-scripts/docs/webpack-configs.md
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Terser is used by default with recent version of webpack (instead of UglifyJS), and its documentation recommends to enable the parallel option to make the build faster:
> Parallelization can speedup your build significantly and is therefore highly recommended.
https://github.com/webpack-contrib/terser-webpack-plugin#parallel
> feat: Make the minification faster

- packages/cozy-scripts/template-vue/.travis.yml
- packages/cozy-scripts/template/.travis.yml
Using the `only` directive prevent tags from being built.
See https://docs.travis-ci.com/user/customizing-the-build#safelisting-or-blocklisting-branches
(regexp test https://regex101.com/r/wsBW0t/1/)
[see @gregorylegarec commit](https://github.com/cozy/cozy-store/pull/551)
> fix(travis): Branches directive 🚑

- package.json
The test:cli rule has been renamed to test:tools in the past. But as test:tools has some overlaps with the test rule, I've fixed it but making the test rule doing something similar to what is on travis.
> chore: Fix yarn test

- packages/cozy-scripts/config/webpack.config.cozy-ui.js
- packages/cozy-scripts/config/webpack.config.css-modules.js
- packages/cozy-scripts/docs/webpack-merge-strategies.md
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/cozy-scripts/test/lib/strategy.config.js
Stylus has its own resolver, but it is slower and it doesn't work when importing a file from another package. It still works because stylus-loader has a fallback on webpack resolver in those cases. But it's faster and, I think, saner to use directly webpack resolver.
See https://github.com/shama/stylus-loader#prefer-webpack-resolving
For example, I've tried on cozy-settings, and yarn build takes 39s before this change, and only 31s after. I also think we win around 8s for yarn watch but it's harder to measure.
> feat: Don't use the slow stylus resolver

- packages/cozy-scripts/config/webpack.environment.dev.js
Since we're using HMR on Drive, we had an error : window is not defined. 
See: https://github.com/webpack/webpack/issues/6642#issuecomment-370222543
> fix: Support window in HMR env

- packages/cozy-scripts/config/webpack.environment.prod.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Resolve the "can't declare twice a const". This is a Safari 10 bug... 
See https://github.com/zeit/next.js/issues/5630 & https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/92
> fix: Safari 10 issue

- .travis.yml
- packages/create-cozy-app/index.js
The node v10 is now required to develop Cozy applications
> Force node v10 usage

- packages/cozy-scripts/scripts/start.js
Remove errors about `Invalid Host/Origin Header` from webpack-dev-server
> Fix HMR with last webpack-dev-server version

- packages/cozy-scripts/package.json
- packages/cozy-scripts/scripts/config.js
- packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
- packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
- packages/cozy-scripts/yarn.lock
Using `--debug` we will now get more timing information during webpack scripts
> Add speead measure webpack plugin on debug mode

- packages/cozy-scripts/config/webpack.config.assets.js
- packages/cozy-scripts/config/webpack.config.manifest.js
- packages/cozy-scripts/config/webpack.config.public.js
- packages/cozy-scripts/config/webpack.environment.dev.js
- packages/cozy-scripts/config/webpack.vars.js
Current master branch is failing creating public assets mainly because we're calling `hasPublic` https://github.com/cozy/create-cozy-app/blob/92601f644474be69174903f32d571ed1985e02ca/packages/cozy-scripts/config/webpack.vars.js#L33  during launch time.
`hasPublic` call https://github.com/cozy/create-cozy-app/blob/92601f644474be69174903f32d571ed1985e02ca/packages/cozy-scripts/utils/paths.js#L20, but `process.env[CTS.ENTRY_EXT]` is not yet set, so hasPublic is failing since it fallbacks to `index.js` and not `index.jsx`
By calling hasPublic when needed seems to work
> fix: Call method when needed not before

- packages/cozy-scripts/config/webpack.config.manifest.js
If those keys are already there, it is surprising for the developer
to have them overriden.
> Do not override lang/locales into manifest

- .travis.yml
- scripts/deploy.sh
Build stages help use have the tests run in parallel and at the end
have a deploy step if the previous stages have finished successfully.
> chore: Reorganize travis.yml to be able to deploy automatically

- packages/cozy-scripts/package.json
- packages/cozy-scripts/template/package.json
When I used cozy-scripts in Banks, I had to install 
eslint-plugin-prettier. AMHA since this is cozy-scripts
that needs it, it should not be installed via the app.
cozy-scripts bears all the tooling dependencies so that
the app can forget about that.
> Move dependencies outside the app

- packages/cozy-scripts/config/webpack.environment.dev.js
- packages/cozy-scripts/package.json
- packages/cozy-scripts/yarn.lock
In 5edd75114, a refactor to extract the public config caused the bar not
to be injected automatically through HtmlWebpackIncludeAssetsPlugin anymore.
This caused `cozy.bar is undefined` problems.
Here, we inject the bar through the ProvidePlugin and automatically inject
the bar's CSS through imports-loader. I refactored a bit to make it clear
that the STACK_ASSETS variable defined to be used in the HTML template is
related to the bar config.
This feature will allow banks to remove its custom code : https://github.com/cozy/cozy-banks/blob/63054a75efd1681f14b36c488f8569b0569d7738/webpack.config.js#L13
> feat: Automatically provide the bar via ProvidePlugin if used through cozy.bar

- packages/cozy-scripts/config/webpack.environment.dev.js
Cozy-Stack still provides CozyClientJS in production and few apps are
still using it. So we need to inject it in dev mode.
> fix: Provide cozyclientjs in dev mode

- packages/cozy-scripts/scripts/start.js
Since the page serving the JS is served by a different host than
the webpack-dev-server, we need to use the allowedHosts setting
to tell webpack that pages served from .cozy.tools domain are
allowed to fetch content from the webpack-dev-server.
> fix: Add allowed hosts to fix "Invalid Host Header" error

- packages/cozy-scripts/config/webpack.config.cozy-ui.js
- packages/cozy-scripts/config/webpack.config.cozy-ui.react.js
- packages/cozy-scripts/config/webpack.config.css-modules.js
- packages/cozy-scripts/config/webpack.config.pictures.js
- packages/cozy-scripts/config/webpack.config.react.js
- packages/cozy-scripts/config/webpack.environment.dev.js
replace "\/" by "(\/|\\)" to be handle by windows
> Fix webpack config for windows

- packages/cozy-scripts/bin/cozy-scripts.js
- packages/cozy-scripts/scripts/check-locales.js
The script checks two locale (JSON) files and outputs the differing
keys. It exits 1 if there are keys that differs. It is used to check
whether a JSON file is up-to-date against another one.
> feat: Add check-locales script

- README.md
- packages/cozy-scripts/README.md
- packages/cozy-scripts/scripts/start.js
- Re-orders some paragraphs to be nearer to related paragraphs
- Correct grammatical errors
- Removes --stack option that we do not use.
IMHO we should not support options that we do not use internally
as we do not have enough bandwidth to improve them, and we do
not fully understand them. We should let the community build
things.
> Simplify README

- packages/cozy-scripts/template/package.json
Creating a new version from scratch result in : "warning package.json: "dependencies" has dependency "cozy-scripts" with range "5.0.1" that collides with a dependency in "devDependencies" of the same name with version "4""
> fix: Use cozy-scripts v5

- packages/cozy-scripts/config/.stylintrc
- packages/cozy-scripts/package.json
- packages/cozy-scripts/yarn.lock
Applications should not have the stylelint dependency, it should
be brought by cozy-scripts, so that it is easily updatable across
our apps.
Likewise, the stylintrc should be shared across our apps. An
application can do
```
stylint src/styles --config node_modules/cozy-scripts/config/.stylintrc
```
> feat: Share .stylintrc

- packages/cozy-scripts/config/webpack.config.base.js
This can help when there are conflicting dependencies, and one
dependent has a dependency inside its own node_modules
Fix https://github.com/cozy/create-cozy-app/issues/1351'
> fix: Add relative node_modules in resolve.modules

- packages/cozy-scripts/config/webpack.config.base.js
The mobile font was not loaded as the stylesheet was put under a folder.
```
main/
banks.css
Lato.woff
```
With this fix, we have
```
main-banks.css
Lato.woff
```
> Fix font loading

- packages/cozy-scripts/bin/cozy-scripts.js
- packages/cozy-scripts/scripts/stackDocker.js
- packages/cozy-scripts/template/README.md
- packages/cozy-scripts/template/package.json
- Remove `--hot` since it's the default now 
- Add two commands to run the docker image (one with CSP enabled, one without)
> docs: Add 2 commands to start the docker image

- packages/cozy-scripts/bin/cozy-scripts.js
- packages/cozy-scripts/scripts/deploy.js
This command is useful for manual adhoc deployments.
It uses argparse inside the script to provide --help `cs deploy --help`.
> feat: Add deploy command using git-directory-deploy

- packages/cozy-scripts/config/webpack.bundle.default.js
- packages/cozy-scripts/config/webpack.config.duplicates.js
- packages/cozy-scripts/package.json
- packages/cozy-scripts/yarn.lock
Outputs warnings if libraries are multiple times in a bundle.
For example in [contacts](https://github.com/cozy/cozy-contacts).
```
WARNING in hoist-non-react-statics
Multiple versions of hoist-non-react-statics found:
2.5.5 ./~/cozy-client/~/hoist-non-react-statics
3.3.0 ./~/hoist-non-react-statics
WARNING in lodash
Multiple versions of lodash found:
4.17.13 ./~/cozy-device-helper/~/lodash
4.17.14 ./~/cozy-client/~/lodash
4.17.15 ./~/lodash
WARNING in prop-types
Multiple versions of prop-types found:
15.6.2 ./~/cozy-client/~/prop-types
15.7.2 ./~/prop-types
WARNING in react
Multiple versions of react found:
16.7.0 ./~/cozy-client/~/react
16.8.6 /Users/cozy/code/cozy/create-cozy-app/packages/cozy-scripts/~/react
WARNING in regenerator-runtime
Multiple versions of regenerator-runtime …
```
> chore: Add duplicate package checker plugin

- packages/cozy-scripts/README.md
Put the start in first,  as  this is preferred over watch and add a precision about services
> docs: watch vs start

- packages/cozy-scripts/template/manifest.webapp
This was causing 403 errors for each app run by CCA
> fix: Add settings permission

- packages/cozy-scripts/scripts/start.js
Since we now use `*.cozy.localhost` for our development purpose, 
let's put it in the allowedHosts in order to avoid a flood of 
"Invalid Host / Origin Header"
> feat: Support cozy.localhost

- packages/cozy-scripts/README.md
- packages/cozy-scripts/config/webpack.bundle.default.js
- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/config/webpack.config.typescript.js
- packages/cozy-scripts/package.json
- packages/cozy-scripts/yarn.lock
This branch will allow Cozy projects to use Typescript files (from node_modules or src).
In order to have a working babel-loader, at the moment you have to `yarn add --dev @babel/preset-env @babel/preset-typescript` in your cozy app root dir (cozy babel preset has to be updated). Then you need to call the presets in `<rootDir>/babel.config.js`, like this: 
```
module.exports = {
presets: ['cozy-app', '@babel/typescript', '@babel/env']
}
```
If you want basic ESLint support you can update your .eslintrc like this (you have to install `@typescript-eslint`): 
```
{
"parser": "@typescript-eslint/parser",
"plugins": ["@typescript-eslint"],
"extends": ["cozy-app/react"],
"rules": {
"react/display-name": "off",
"no-unused-vars": "warn",
"no-case-declarations": "warn"
}
}
```
if you want advanced …
> feat: add typescript compilation

- .github/auto-merge.yml
Automerge bot is currently broken because it tries to create a merge commit which is forbidden on this repo.
This PR switches automerge bot to rebase merge strategy.
Also delete source branch after merge (only if it resides in the same repo)
> chore: use rebase merge method for automerge bot

- packages/cozy-scripts/config/webpack.environment.dev.js
Had a regression on webpack dev serv on cozy-banks because the config was trying to resolve cozy-bar minified css which doesn't exist in the cozy-bar version (>=8) used by cozy-banks (the css is inside the js).
A quick fix is to remove the rule breaking the build for all apps using cozy-bar >=8
> fix : Do not import cozy-bar css in v8 apps

- .travis.yml
Pipeline lasts hour because cache got issues managing build using node 12 and node 16. I removed it.
Before: 1h22min => https://app.travis-ci.com/github/cozy/create-cozy-app/builds/247268281
After: 22min => https://app.travis-ci.com/github/cozy/create-cozy-app/builds/247280583
> chore(travis): remove cache and check how long is pipeline

- packages/cozy-scripts/config/webpack.environment.dev.js
When we use the `yarn start` command we get this error message in console
I propose this fix (with the `cozy-client` decoupling proposed in this PR #1446 )
> fix: Crashes in dev mode

- packages/cozy-scripts/scripts/start.js
Useful for Cozy Native App
according to:
https://github.com/cozy/cozy-react-native/blob/master/README.md#working-with-locally-hosted-webviews
> feat(scripts): start allows hosts from nip.io

- packages/cozy-scripts/config/webpack.config.base.js
Main reason is Drive needs CSS styles to be served in public folder to
be viewed inside "Public Views" (after Sharings)
fix #1360
addendum to #1355
> fix(scripts): webpack build css inside different folders AND main folders

- packages/cozy-scripts/config/webpack.environment.dev.js
This will make debugging easier.
It makes no sense to use the prod cozy-bar when app is in dev mode
With this fix, both the app and the bar will share the same context
> fix: Import dev cozy-bar in dev env

- packages/cozy-scripts/scripts/build.js
when debugging a build failing, I needed to get this property to get stats.
How to reproduce that error:
- go in a cozy application, make the build failed, example in cozy-settings, move the withLocales inside the locales folder, and yarn build.
> fix(build): Handling errors stats fix

- packages/cozy-scripts/config/webpack.config.base.js
- packages/cozy-scripts/config/webpack.config.services.js
- packages/cozy-scripts/config/webpack.target.browser.js
- packages/cozy-scripts/config/webpack.vars.js
The CSS file that the public page needs is kept in the public folder.
fix: https://github.com/cozy/create-cozy-app/pull/1457
Example of the "build" folder (CSS view):
Before:
```
/app
<appSlug>.<id>.min.css
/intents
<appSlug>.<id>.min.css
/public
<appSlug>.<id>.min.css
/vendors
app-<appSlug>.<id>.min.css
intents-<appSlug>.<id>.min.css
public-<appSlug>.<id>.min.css
vendors-<appSlug>.<id>.min.css
```
After:
```
/app
/intents
/public
<appSlug>.<id>.min.css
/vendors
app-<appSlug>.<id>.min.css
intents-<appSlug>.<id>.min.css
vendors-<appSlug>.<id>.min.css
```
Tested with the Drive & CoachCO2 apps.
> fix(scripts): Webpack must not duplicate the css files

- packages/cozy-scripts/config/webpack.config.manifest.js
This reverts commit f28281ca5b731e6c56c145866df6a0db7b394634.
This commit wasn't working for locales. It's create side effect on the store like hiding the app name and also increase the bundle size of the app.
> Revert "fix: Merge locales and langs entry in manifest"

- packages/cozy-scripts/template/app/src/targets/browser/index.ejs
ThemeCSS should be the latest injected CSS
since it can override css's variables. 
It should be after the CSS from the app but also
after the CozyBar since this lib inject its own 
CSS
> fix: Css Order

- packages/cozy-scripts/template/README.md
Transifex has migrated to a new CLI after migrating their API to v3. I have updated the documentation to match this change and also have a few lines on our methodology with the Transifex Github integration
> docs: Update transifex doc about in the readme

- packages/cozy-scripts/config/webpack.config.cozy-bar-v7.js
- packages/cozy-scripts/config/webpack.config.public.js
- packages/cozy-scripts/config/webpack.vars.js
I made a mistake in a previous [PR](https://github.com/cozy/create-cozy-app/pull/1488) to extract cozy-bar v7 config. If you add version 7, this creates an unwanted public entry point that copies the bar source file to the public folder. This causes the build folder to grow without ever being used 🙁
This PR aims to correct this problem by only copying assts when the application needs to have the public configuration from which the config originally came (cf: [old code](https://github.com/cozy/create-cozy-app/commit/659644fa8b7b4954540ba4b698aa5f2353a9775d))
> fix: Copy cozy-bar v7 assets only if should add public config

- packages/cozy-scripts/bin/cozy-scripts.js
This change is required for Node versions >= 17
Following the issue related to OpenSSL (https://github.com/webpack/webpack/issues/13572), we decided to use this solution [https://github.com/webpack/webpack/issues/13572#issuecomment- 923736472](https://github.com/webpack/webpack/issues/13572#issuecomment-923736472), compatible with Node version 16 to 20
> Force hash `sha256` instead of `md4`

- packages/cozy-scripts/scripts/test.js
We recently realized that the `NODE_ENV` variable was not defined during application testing.
If your application uses cozy-scripts to run tests, you can remove `env NODE_ENV=test` from your script
> feat: Force NODE_ENV to "test" when run it
